// <auto-generated />
namespace netzkern.MyBookstore.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PrimaryKeyDefinedForOrderAndPersonAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimaryKeyDefinedForOrderAndPersonAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202012030945204_PrimaryKeyDefinedForOrderAndPersonAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
